version: '3.8'

services:
  configurator:
    image: frappe/erpnext-worker:version-15
    command: >
      bash -c "bench set-config -g db_host db &&
      bench set-config -g redis_cache redis://redis-cache:6379 &&
      bench set-config -g redis_queue redis://redis-queue:6379 &&
      bench set-config -g redis_socketio redis://redis-queue:6379"
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  backend:
    image: frappe/erpnext-worker:version-15
    depends_on:
      - db
      - redis-cache
      - redis-queue
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ../..:/workspace
    command: >
      bash -c "bench get-app /workspace/salon_booking &&
      bench new-site --mariadb-root-password admin --admin-password admin salon.localhost &&
      bench --site salon.localhost install-app salon_booking &&
      bench start"
    ports:
      - '8000:8000'

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:6.2-alpine

  redis-queue:
    image: redis:6.2-alpine

volumes:
  sites:
  db-data:
